# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
 repositories:
   - repository: azDeployments
     type: git
     name: AzDeployments/powershell-files

trigger:
- jm-development

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: "UCare CosmosDB NoSQL Seed Data Test"
  inputs:
    filePath: 'actual-scripts/InsertSeedDataIntoCosmosDBNoSQL.ps1'