variables:
- group: UCare-DEV-JM
- name: vmImageName
  value: $(vmImageName)

resources:
 repositories:
   - repository: azDeployments
     type: git
     name: UCare - Experimental Research for Azure Cosmos DB/AzDeployments
     ref: jm-development

pool:
  vmImage: $(vmImageName)

steps:
- task: AzurePowerShell@5
  displayName: "UCare CosmosDB NoSQL Seed Data Test"
  inputs:
    azureSubscription: $(AzureServiceConnection)'
    ScriptType: 'FilePath'
    ScriptPath: '$(CosmosPopulateNoSqlScript)'
    ScriptArguments: -resourceGroupName '$(CosmosResourceGroupName)' -dataInputType '$(DataInputType)' -dummyData '$(NoSQLDummyData)'
    azurePowerShellVersion: 'LatestVersion'
