# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- jm-development

pool:
  vmImage: 'windows-latest'

steps:
- pwsh: |
    Get-ChildItem $(Build.SourcesDirectory) -Recurse
  name: DebugCheckout
  displayName: Debug script checkout
- task: PowerShell@2
  displayName: "UCare CosmosDB NoSQL Seed Data"
  inputs:
    filePath: '$(Build.SourcesDirectory)/powershell-files/actual-scripts/InsertSeedDataIntoCosmosDBNoSQL.ps1'